version: '3.7'

x-args: &ARGS
  ECR_DOMAIN: ${ECR_DOMAIN}
  STAGE: ${STAGE}

x-build-option: &BUILD_OPTION
  context: .
  cache_from:
    - ${ECR_DOMAIN}/wechicken
  dockerfile: ./server.Dockerfile

services:
  database:
    image: wechicken-mysql:latest
    build:
      context: .
      cache_from:
        - wechicken-mysql:latest
      dockerfile: ./database.Dockerfile
    ports:
      - '3307:3306'
  local:
    image: ${ECR_DOMAIN}/wechicken:latest
    build:
      <<: *BUILD_OPTION
      args: *ARGS
    ports:
      - '8090:3000'
    depends_on:
      - database
    command: ['./wait-for-it.sh', 'database:3306', '--', 'npm', 'run', 'start:prod']
    links:
      - database
  development:
    image: ${ECR_DOMAIN}/wechicken:development
    build:
      <<: *BUILD_OPTION
      args: *ARGS
