module.exports = {
  STAGE: process.env.STAGE,
  DB_HOST: process.env.DB_HOST,
  DB_PORT: process.env.DB_PORT,
  DB_USERNAME: process.env.DB_USERNAME,
  DB_PASSWORD: process.env.DB_PASSWORD,
  DB_DATABASE: process.env.DB_DATABASE,
  GOOGLE_AUTH_CLIENT_ID: process.env.GOOGLE_AUTH_CLIENT_ID,
  GOOGLE_AUTH_SECRET_KEY: process.env.GOOGLE_AUTH_SECRET_KEY,
  EXTERNAL_AWS_ACCESS_KEY_ID: process.env.EXTERNAL_AWS_ACCESS_KEY_ID,
  EXTERNAL_AWS_SECRET_ACCESS_KEY: process.env.EXTERNAL_AWS_SECRET_ACCESS_KEY,
  EXTERNAL_AWS_S3_BUCKET_NAME: process.env.EXTERNAL_AWS_S3_BUCKET_NAME,
};
