service: wechicken

app: wechicken

plugins:
  - serverless-offline
  # - serverless-plugin-optimize
  - serverless-plugin-warmup

provider:
  lambdaHashingVersion: '20201221'
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${env:STAGE}
  region: ap-northeast-2
  apiName: wechicken-api
  timeout: 300
  environment: ${file(./env.js)}
  iam:
    role: arn:aws:iam::193634490577:role/LambdaAPIRole
  vpc:
    securityGroupIds:
      - sg-04614be6f330572c2
      - sg-07caaa2457111114d
    subnetIds:
      - subnet-0d11a1e045427c5ff
      - subnet-04c1c8412c1c88590
      - subnet-04ae0ca30473b3882
      - subnet-0982f62bc41ea309d
<<<<<<< HEAD
  package:
  pattern:
    - dist/**
    - node_modules/**
=======
>>>>>>> 541197795e08124359f8335e063df45a37dd8363

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY

package:
  patterns:
    - dist/**
    - node_modules/**

custom:
  serverless-offline:
    httpPort: 8090
    noPrependStageInUrl: true
  # optimize:
  #   external: ['swagger-ui-dist']
  warmup:
    - production
