name: wechicken-development

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Serverless Node:${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Ci Test
        env:
          STAGE: ${{ secrets.NODE_ENV }}
        run: npm run test:CI

      - name: DEPLOY
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
        run: npm run deploy
