name: wechicken-development

on:
  push:
    branches: [ development ]

jobs:
  build:
    environment: development
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add profile credentials to ~/.aws/credentials 
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile wechicken
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile wechicken
          aws configure set region ${{ secrets.AWS_REGION }} --profile wechicken

      - name: Serverless Node:${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: direnv
        uses: HatsuneMiku3939/direnv-action@v1

      - name: CI Test
        run: npm run test:CI

      - name: DEPLOY
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          STAGE: ${{ secrets.STAGE }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          GOOGLE_AUTH_CLIENT_ID: ${{ secrets.GOOGLE_AUTH_CLIENT_ID }}
        run: npm run deploy
