name: wechicken-CI

on:
  push:
    branches: [ feature/*, main, develop ]
  pull_request:
    branches: [ main, develop, development, production ]

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [12.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: direnv
        uses: HatsuneMiku3939/direnv-action@v1

      - name: CI Node:${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run test:CI
